### ISSUE TITLE
Error: Illegal value 47 for `line` 

### ISSUE THREAD

**Issue by jrieken** [shardulm94/vscode-trailingspaces#3]
From the vscode error telemetry

```
Error: Illegal value 47 for `line` 
at t.lineAt (\out\vs\workbench\node\pluginHostProcess.js:18:29390) 
at Object.t.lineAt (\out\vs\workbench\node\pluginHostProcess.js:18:28204) 
at TrailingSpaces.matchTrailingSpaces (\shardulm94.trailing-spaces-0.2.7\out\src\trailing-spaces\trailing-spaces.js:150:95) 
at \shardulm94.trailing-spaces-0.2.7\out\src\trailing-spaces\trailing-spaces.js:59:23 
at e.invoke (\out\vs\workbench\node\pluginHostProcess.js:7:14035) 
at e.fire (\out\vs\workbench\node\pluginHostProcess.js:7:15488) 
at e._acceptSelectionsChanged (\out\vs\workbench\node\pluginHostProcess.js:19:7900) 
at t.e.handle (\out\vs\workbench\node\pluginHostProcess.js:15:12835) 
at c (\out\vs\workbench\node\pluginHostProcess.js:11:16222) 
at h (\out\vs\workbench\node\pluginHostProcess.js:11:16882) 
```

**Comment by shardulm94** [comment]
Hi, can you help me reproduce this issue?
Maybe a sample file to reproduce this and which area was selected or where the cursor was?
Also, default settings that were overridden by you, if any.

**Comment by jrieken** [comment]
Not really because this is from our automated error telemetry. Tho the error is being thrown here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostDocuments.ts#L315. So it seems like you are accessing a line that doesn't exist

**Comment by shardulm94** [comment]
Alright, I will look into it.

**Comment by shardulm94** [comment]
Fixed in https://github.com/Microsoft/vscode/issues/5362 https://github.com/Microsoft/vscode/commit/b02c4facaf2c3b983af7f8e6617bf54ce2261259

**Comment by kenokabe** [comment]
@shardulm94 Hi, 
I still have this issue: https://github.com/Microsoft/vscode/issues/5362

>textEditor points to the old document,

> there were two `onDidChangeTextEditorSelection` events.
The second one has the correct file and selection, but in the first event the file and selection do not match.

I am using 
```
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

Is this really fixed? Thanks!
